// Fetch Auth Data
export const FETCH_AUTH_DATA_REQUEST = "FETCH_AUTH_DATA_REQUEST";
export const FETCH_AUTH_DATA_SUCCESS = "FETCH_AUTH_DATA_SUCCESS";
export const FETCH_AUTH_DATA_FAILURE = "FETCH_AUTH_DATA_FAILURE";
